waistpitch: 1.0        #1.0 表示腰部弯 pitch 角度为上半身 pitch 角度的幅度比率  默认值是1.0,范围[0.0,1.2]
waistyaw: 0.2          #0.3 表示腰部转 yaw 角度为上半身 yaw 角度的幅度比率  默认值是0.4,范围[0.0,0.5]
waistroll: 0.0        #0.05 表示腰部侧 roll 角度为上半身 roll 角度的幅度比率  默认值是0.05,范围[0.0,0.1]
